app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('/', function() {
    return view('auth.login');
});

// Authentication routes...
Route::get('login', [
    'uses'  => 'Auth\AuthController@getLogin',
    'as'    => 'login'
]);

Route::post('login', 'Auth\AuthController@postLogin');

Route::get('logout', [
    'uses'  => 'Auth\AuthController@getLogout',
    'as'    => 'logout'
]);

// Registration routes...
Route::get('register', [
    'uses'  => 'Auth\AuthController@getRegister',
    'as'    => 'register'
]);
Route::post('register', 'Auth\AuthController@postRegister');


/*
 *
 */
// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');


/*
 * PRUEBA: Indentificar si un usuario esta conectado
 * Grupos de rutas de laravel
 * app/Http/Kernel.php
 */

Route::group(['middleware' => 'auth'], function () {

    /*
     * ADMIN
     */
    Route::get('admin', [
        'uses'  => 'AdminController@index',
        'as'    => 'panel'
    ]);

    Route::get('admin/{id}/editar', [
        'uses' => 'AdminController@edit',
        'as' => 'admin.edit'
    ]);

    Route::put('admin/{id}/update', [
        'uses' => 'AdminController@update',
        'as' => 'admin.update'
    ]);


    Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {

        Route::resource('colecciones', 'FormsController');
        Route::resource('complements', 'ComplementsController');
        Route::resource('inputs', 'InputsController');

        // DIBUJAR FORMULARIO
        Route::get('coleccion/{id}/form', [
            'uses'  => 'InputsController@drawForm',
            'as'    => 'form'
        ]);

        // SAVE FORMULARIO
        Route::get('coleccion/form/{id}/new', [
            'uses'  => 'DvarcharController@storeFormData',
            'as'    => 'admin.colecciones.form.data.store'
        ]);

        // SHOW DATA FROM COLLECTION
        Route::get('coleccion/form/{id}/lista', [
            'uses'  => 'DvarcharController@index',
            'as'    => 'admin.colecciones.form.data.index'
        ]);

        // DESTROY ROW DATA
        Route::delete('coleccion/form/lista/row/{id}/delete', [
            'uses'  => 'DvarcharController@destroy',
            'as'    => 'admin.colecciones.form.data.list.destroy'
        ]);

        // SAVE FORMULARIO
        Route::put('coleccion/form/lista/row/{id}/update', [
            'uses'  => 'DvarcharController@update',
            'as'    => 'admin.colecciones.form.data.list.update.input'
        ]);


        /*
         * STATISTIC CONTROLLER
         */

        // VIEW STATISTICS
        Route::get('estadisticas', [
            'uses'  => 'StatisticController@index',
            'as'    => 'admin.statistics.index'
        ]);

        Route::post('estadisticas/colums', [
            'uses'  => 'StatisticController@showColums',
            'as'    => 'admin.statistics.index.columns'
        ]);

        Route::post('estadisticas/colums/data', [
            'uses'  => 'StatisticController@getDataColumns',
            'as'    => 'admin.statistics.index.columns.data'
        ]);

        Route::get('estadisticas/dispersion/puntos/data', [
           'uses'   => 'StatisticController@getPoints' ,
            'as'    => 'statistics.dispersion.puntos.data'
        ]);



        /*
         * EXCEL
         */

        Route::get('export-all', [
            'uses'  => 'ExcelController@exportAll',
            'as'    => 'admin.export.all'
        ]);

        Route::post('{id}/import-all', [
            'uses'  => 'ExcelController@importAllToCollection',
            'as'    => 'admin.import.all'
        ]);

    });


});

resources/views/admin/colections/create.blade.php
@extends('layout-admin')

@section('title', @trans('title.home'))

@section('content')

        <!-- REVISAR -->
    <div class="head-fixed">
        <div class="head-menu">
            <h1><span><img src="{{ asset('/images/icon-complements.svg') }}"></span> <span> > </span> NUEVA COLECCIÓN </h1>
        </div>
    </div>

    <div class="container-inputs-list min-top">

        <div class="container-form">
            <div class="container-form-titulo">
                <div id="container-form-icon-collection" class="container-form-icon"></div>
                <div><h3>Nueva colección</h3></div>
            </div>

            @include('partials.errors')
            {!! Form::open(['route' => 'admin.colecciones.store', 'method' => 'POST']) !!}

                @include('admin.colections.partials.filds')
                <a href="{{ url('/admin/colecciones') }}" class="btn btn-danger">Cancelar</a>
                <button type="submit" class="btn btn-primary">@lang('collections.btn_new_collection')</button>

            {!! Form::close() !!}
        </div>

    </div>



@endsection

resources/views/admin/colections/edit.blade.php
@extends('layout-admin')

@section('title', @trans('title.home'))

@section('content')



    <!-- REVISAR -->
    <div class="head-fixed">
        <div class="head-menu">
            <h1><span><img src="{{ asset('/images/icon-complements.svg') }}"></span> <span> > </span> {{ $form->name  }} </h1>
            @include('admin.colections.complements.partials.menu')
        </div>
    </div>


    <div class="container-inputs-list min-top">

        <div id="new-register" class="container-form">
            <div class="container-form-titulo">
                <div id="container-form-icon-collection" class="container-form-icon"></div>
                <div><h3>Editar colección {{ $form->name  }}</h3></div>
            </div>

            @include('partials.errors')
            {!! Form::model($form, ['route' => ['admin.colecciones.update', $form], 'method' => 'PUT']) !!}

                @include('admin.colections.partials.filds')
                <button type="submit" class="btn btn-primary float-izq">@lang('collections.btn_edit_collection')</button>

            {!! Form::close() !!}

            @include('admin.colections.partials.delete')

        </div>


        <div id="new-register-import" class="container-form">
            <div class="container-form-titulo">
                <div id="container-form-icon-collection" class="container-form-icon"></div>
                <div><h3>Menú</h3></div>
            </div>

            <div class="btn-group-vertical" role="group" aria-label="Vertical button group">


                <a class="btn" href="{{ route('form', $form) }}">Nuevo registro</a>
                <a class="btn" href="{{ route('admin.colecciones.form.data.index', $form) }}">Gestionar registros</a>
                <a class="btn" href="{{ route('admin.complements.edit', $form) }}">Complements</a>
                <a class="btn" href="{{ url('/admin/colecciones') }}">Cerrar colección</a>

                <!--
                <button type="button" class="btn btn-default">Nuevo registro</button>
                <button type="button" class="btn btn-default">Gestionar registros</button>
                <div class="btn-group" role="group">
                    <button id="btnGroupVerticalDrop1" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Complements
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="btnGroupVerticalDrop1">
                        <li><a href="#">Dropdown link</a></li>
                        <li><a href="#">Dropdown link</a></li>
                    </ul>
                </div>
                <button type="button" class="btn btn-default">Editar colección</button>
                <button type="button" class="btn btn-default">Ver mis colecciones</button>
                <div class="btn-group" role="group">
                    <button id="btnGroupVerticalDrop2" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="btnGroupVerticalDrop2">
                        <li><a href="#">Dropdown link</a></li>
                        <li><a href="#">Dropdown link</a></li>
                    </ul>
                </div>
                <div class="btn-group" role="group">
                    <button id="btnGroupVerticalDrop3" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="btnGroupVerticalDrop3">
                        <li><a href="#">Dropdown link</a></li>
                        <li><a href="#">Dropdown link</a></li>
                    </ul>
                </div>
            </div>
            -->

        </div>


    </div>

@endsection

resources/views/admin/colections/index.blade.php
@extends('layout-admin')

@section('title', @trans('title.home'))

@section('content')

    @if(Session::has('message'))
        <div class="alert alert-success">
            <div class="alert-title-success">
                Estado operación
            </div>
            <ul>
                <li>{{ Session::get('message') }}</li>
            </ul>
        </div>
    @endif
        <div class="head-fixed">
            <div class="head-menu">
                <h1><span><img src="{{ asset('/images/icon-complements.svg') }}"></span> <span> > </span> Colecciones de datos</h1>
            </div>

            <div>
                <p>Tienes <span class="badge">{{ $forms->total() }}</span> colecciones</p>
            </div>

        </div>

        <div class="container-inputs-list" id="datos">

            <div class="collection-list-new">
                <div class="collection-new-text">
                    <p>Nueva colección</p>
                </div>
                <div class="collection-new-icon">
                    <a href="{{ route('admin.colecciones.create') }}"><div></div></a>
                </div>
            </div>

            @foreach($forms as $form)
            <div class="collection-list" data-id="{{ $form->id }}">
                <div class="collection-litle">
                    <p>{{ $form->name }}</p>
                </div>
                <div class="collection-info">
                    <p>{{ $form->description }}</p>
                </div>
                <div class="collection-menu">
                    <ul>
                        <li><a href="{{ route('admin.colecciones.edit', $form) }}">Abrir</a></li>
                        <li><a href="#!" class="btn-eliminar">Eliminar</a></li>
                    </ul>
                </div>
            </div>
            @endforeach

            <div class="listar-data">
                {!! $forms->render() !!}
            </div>
        </div>

    {!! Form::open(['route' => ['admin.colecciones.destroy', ':USER_ID'], 'method' => 'DELETE', 'id' => 'form-delete']) !!}
    {!! Form::close() !!}
@endsection

@section('scripts')
    <script src="{{ asset('/js/collections.js') }}"></script>
@endsection